### ISSUE TITLE
如何在自定义数据山个训练Hyper-yolov1.1模型？

### ISSUE THREAD

**Issue by 1404561326521** [iMoonLab/Hyper-YOLOv1.1#2]
作者您好，感谢您们的开源工作，我想在自己数据集上训练Hyper-yolov1.1模型，train.py中的“--cfg”该加载哪个配置文件？另外关于分割任务的预训练权重我好像没找到下载地址，望回复一下，谢谢！
![image](https://github.com/user-attachments/assets/6dcd3419-683c-4743-be8e-f080c94a72c5)

**Comment by jianganghuang** [comment]
感谢您的关注，虽然我们在Hyper-YOLOv1.1版本里并没有进行分割任务的模型训练，但在1.0版本里详尽实验证明了Hyper-YOLO方法可以轻松地从检测任务迁移到分割任务，并能取得一致的性能提升。在Hyper-YOLOv1.1版本您也可以很轻易的将检测模型修改为分割模型，只需要简单的将检测head修改为分割head即可。
具体来说: 以gelan-s-hyper.yaml和yolov9-s-hyper.yaml为例
1. 你可以在segment文件夹里新建gelan-s-hyper-seg.yaml和yolov9-s-hyper-seg.yaml, 复制检测模型配置yaml文件对应的内容。
2. 然后将yaml文件最后一行的Detect或DualDetect切换为Segment, DSegment或DualSegment。
3. 训练过程和方法你可以参照yolov9和我们Hyper-YOLOv1.1检测模型的介绍。
此外，关于Hyper-YOLOv1.1分割模型的预训练权重，您也可以选择加载检测模型的权重来初始化。

**Comment by 1404561326521** [comment]
> 感谢您的关注，虽然我们在Hyper-YOLOv1.1版本里并没有进行分割任务的模型训练，但在1.0版本里详尽实验证明了Hyper-YOLO方法可以轻松地从检测任务迁移到分割任务，并能取得一致的性能提升。在Hyper-YOLOv1.1版本您也可以很轻易的将检测模型修改为分割模型，只需要简单的将检测head修改为分割head即可。 具体来说: 以gelan-s-hyper.yaml和yolov9-s-hyper.yaml为例
> 
> 1. 你可以在segment文件夹里新建gelan-s-hyper-seg.yaml和yolov9-s-hyper-seg.yaml, 复制检测模型配置yaml文件对应的内容。
> 2. 然后将yaml文件最后一行的Detect或DualDetect切换为Segment, DSegment或DualSegment。
> 3. 训练过程和方法你可以参照yolov9和我们Hyper-YOLOv1.1检测模型的介绍。
>    此外，关于Hyper-YOLOv1.1分割模型的预训练权重，您也可以选择加载检测模型的权重来初始化。

好的，感谢
